config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#index'

  resources :articles

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  validates :content, presence: true

  scope :recent, -> { order("id DESC") }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles

  validates :user_name, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [:user_name]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :redirect_to_index, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.includes(:user).recent
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path, notice: '投稿しました。'
    else
      flash.now[:alert] = '本文が入力されていません。'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.user_id == current_user.id
      if @article.update(article_params)
        redirect_to root_path, notice: '編集しました。'
      else
        flash.now[:alert] = '本文が入力されていません。'
        render :edit
      end
    end
  end

  def destroy
    @article.destroy if @article.user_id == current_user.id
    redirect_to root_path, notice: '削除しました。'
  end

  private

  def article_params
    params.require(:article).permit(:content, images: []).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def redirect_to_index
    unless user_signed_in?
      redirect_to root_path, notice: 'ログインしてください。'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.recent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="container col-sm-6 border-bottom mt-2">
  <div class="float-left form-inline">
    <%= link_to user_path(article.user.id) do %>
      <div class="text-body font-weight-bold"><%= article.user.user_name %></div>
    <% end %>
    <small class="text-body text-muted ml-3"><%= article.created_at.in_time_zone('Tokyo') %></small>
  </div>
  <div class="dropdown float-right">
    <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Menu
    </button>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
      <% unless controller.controller_name == "articles" && controller.action_name == "show" %>
        <%= link_to "Detail", article_path(article), class: "dropdown-item" %>
      <% end %>
      <% if user_signed_in? && article.user_id == current_user.id %>
        <%= link_to "Edit", edit_article_path(article), class: "dropdown-item" %>
        <%= link_to "Delete", article_path(article), method: :delete, class: "dropdown-item" %>
      <% end %>
    </div>
  </div>
  <div class="clearfix"></div>
  <p><%= simple_format(article.content) %></p>
  <% if article.images %>
    <% article.images.count.times do |i| %>
      <%= image_tag(article.images[i]) %>
    <% end %>
  <% end %>
</div>

app/views/articles/_editer.html.erb
<div class="row">
  <%= form_for @article, html: {class: "col s8 offset-s2"} do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :content, id: "textarea1", class: "materialize-textarea", autofocus: true %>
        <%= f.label :content, "本文", for: "textarea1" %>
        <%= f.submit "送信", class: "waves-effect waves-light btn"%>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'share/editer', article: @article %>

app/views/articles/index.html.erb
<h5 class="text-center border">投稿一覧</h5>
<%= render @articles %>

app/views/articles/new.html.erb
<%= render 'share/editer', article: @article %>

app/views/articles/show.html.erb
<%= render @article %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>makoto's Labo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>

    <%= render 'share/navbar' %>

    <%= yield %>

  </body>
</html>

app/views/share/_editer.html.erb
<div class="container col-sm-6 mt-3">
  <%= form_with(model: article, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :content, "本文", for: "textarea1" %>
      <%= f.text_area :content, id: "textarea1", class: "form-control", rows: "5", autofocus: true %>
      <%= f.label :image %>
      <%= f.file_field :images, multiple: true %>
      <%= f.submit "送信", class: "btn btn-primary float-right mt-2"%>
    </div>
  <% end %>
</div>

app/views/share/_navbar.html.erb
<header class="sticky-top bg-dark">
  <div class="container">
    <nav class="navbar navbar-expand-sm navbar-light">
      <%= link_to "makoto's Labo", root_path, class:"navbar-brand text-white" %>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="menu" class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_user.id), class: "nav-link text-muted" %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿する", new_article_path, class: "nav-link text-muted" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-muted" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-muted" %>
            </li class="nav-item">
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link text-muted" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/users/show.html.erb
<% if user_signed_in? && @user.id == current_user.id %>
  <h5 class="text-center border">マイページ</h5>
<% else %>
  <h5 class="text-center border"><%= @user.user_name %>さんの投稿一覧</h5>
<% end %>
<%= render @articles %>